### ISSUE TITLE
curses.h

### ISSUE THREAD

**Issue by IntelligenceInside** [vigna/ne#112]
hi, on compile on alpine 3.17, i'm getting error,

ln -sf ../doc/version.texinfo
c99 -std=c99 -Wall -Wno-parentheses -fno-strict-aliasing -flto=auto -ffat-lto-objects -Wp,-D_FORTIFY_SOURCE=2 -D_REGEX_LARGE_OFFSETS -D_GNU_SOURCE -DSTDC_HEADERS -DHAVE_SNPRINTF   -O3 -DNDEBUG      -c -o actions.o actions.c
In file included from actions.c:22:
ne.h:44:10: fatal error: **curses.h:** No such file or directory
   44 | #include <curses.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: actions.o] Error 1

**Comment by utoddl** [comment]
How are you invoking `make`, and from what directory (the top of the project or `src`)?

Is there anything else on alpine 3.17 that influences the build?

Although it may not apply on alpine, the `ne.spec` file (which controls rpm builds) lists the following requirements:

```
Requires: ncurses
BuildRequires: gcc
BuildRequires: ncurses-devel
BuildRequires: make
BuildRequires: bash
BuildRequires: perl
BuildRequires: texinfo
BuildRequires: sed
```
Alpine likely has equivalently named packages. It sounds like you may need to install the alpine equivalent of `ncurses-devel`.

**Comment by utoddl** [comment]
I'm guessing "ncurses-dev":

https://pkgs.alpinelinux.org/package/edge/main/armhf/ncurses-dev
